--------------------------------------------------------
--  File created - sobota-stycznia-09-2016   
--------------------------------------------------------
DROP TABLE "GOSPODARRZ"."ADDRESS" cascade constraints;
DROP TABLE "GOSPODARRZ"."EVENT" cascade constraints;
DROP TABLE "GOSPODARRZ"."OBJECT" cascade constraints;
DROP TABLE "GOSPODARRZ"."ORDR" cascade constraints;
DROP TABLE "GOSPODARRZ"."PRIVILIGE" cascade constraints;
DROP TABLE "GOSPODARRZ"."STATUS" cascade constraints;
DROP TABLE "GOSPODARRZ"."USR" cascade constraints;
DROP TABLE "GOSPODARRZ"."USROBJECT" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."ADDRESS" 
   (	"ID" NUMBER(*,0), 
	"CITY" VARCHAR2(64 BYTE), 
	"STREET" VARCHAR2(64 BYTE), 
	"NUMB" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."EVENT" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"PLACE" NUMBER(*,0), 
	"MAX_TICKETS" NUMBER(*,0), 
	"TIME" DATE, 
	 CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table OBJECT
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."OBJECT" 
   (	"ID" NUMBER(*,0), 
	"ADDRESS" NUMBER(*,0), 
	 CONSTRAINT "OBJECT_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table ORDR
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."ORDR" 
   (	"ID" NUMBER(*,0), 
	"USR" NUMBER(*,0), 
	"EVENT" NUMBER(*,0), 
	"STATUS" NUMBER(*,0), 
	 CONSTRAINT "ORDR_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table PRIVILIGE
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."PRIVILIGE" 
   (	"ID" NUMBER(*,0), 
	"VALUE" VARCHAR2(5 BYTE), 
	 CONSTRAINT "PRIVILIGE_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."STATUS" 
   (	"VALUE" VARCHAR2(64 BYTE), 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USR
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."USR" 
   (	"ID" NUMBER(*,0), 
	"ADDRESS" NUMBER(*,0), 
	"EMAIL" VARCHAR2(64 BYTE), 
	"PHONE" VARCHAR2(64 BYTE), 
	"PRIVILIGES" NUMBER(*,0), 
	"LOGIN" VARCHAR2(64 BYTE), 
	"PASSWD" VARCHAR2(64 BYTE), 
	 CONSTRAINT "USR_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table USROBJECT
--------------------------------------------------------

  CREATE TABLE "GOSPODARRZ"."USROBJECT" 
   (	"ID" NUMBER(*,0), 
	"USR" NUMBER(*,0), 
	"OBJECT" NUMBER(*,0), 
	 CONSTRAINT "USROBJECT_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."ADDRESS_PK" ON "GOSPODARRZ"."ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."ID" ON "GOSPODARRZ"."STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."USR_PK" ON "GOSPODARRZ"."USR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."ORDR_PK" ON "GOSPODARRZ"."ORDR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIVILIGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."PRIVILIGE_PK" ON "GOSPODARRZ"."PRIVILIGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."EVENT_PK" ON "GOSPODARRZ"."EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OBJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."OBJECT_PK" ON "GOSPODARRZ"."OBJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USROBJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOSPODARRZ"."USROBJECT_PK" ON "GOSPODARRZ"."USROBJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRIVILIGE
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."PRIVILIGE" ADD CONSTRAINT "PRIVILIGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."PRIVILIGE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."PRIVILIGE" MODIFY ("VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USR
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("PRIVILIGES" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" MODIFY ("PASSWD" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USR" ADD CONSTRAINT "USR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USROBJECT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."USROBJECT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USROBJECT" MODIFY ("USR" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USROBJECT" MODIFY ("OBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."USROBJECT" ADD CONSTRAINT "USROBJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."EVENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."EVENT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."EVENT" MODIFY ("PLACE" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."EVENT" MODIFY ("MAX_TICKETS" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."EVENT" MODIFY ("TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDR
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."ORDR" ADD CONSTRAINT "ORDR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."ORDR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ORDR" MODIFY ("USR" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ORDR" MODIFY ("EVENT" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ORDR" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."STATUS" ADD CONSTRAINT "STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."STATUS" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."STATUS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OBJECT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."OBJECT" ADD CONSTRAINT "OBJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."OBJECT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."OBJECT" MODIFY ("ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ADDRESS" MODIFY ("NUMB" NOT NULL ENABLE);
 
  ALTER TABLE "GOSPODARRZ"."ADDRESS" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."EVENT" ADD CONSTRAINT "EVENT_FK1" FOREIGN KEY ("PLACE")
	  REFERENCES "GOSPODARRZ"."OBJECT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJECT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."OBJECT" ADD CONSTRAINT "OBJECT_FK1" FOREIGN KEY ("ADDRESS")
	  REFERENCES "GOSPODARRZ"."ADDRESS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDR
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."ORDR" ADD CONSTRAINT "ORDR_FK1" FOREIGN KEY ("EVENT")
	  REFERENCES "GOSPODARRZ"."EVENT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."ORDR" ADD CONSTRAINT "ORDR_FK2" FOREIGN KEY ("USR")
	  REFERENCES "GOSPODARRZ"."USR" ("ID") ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."ORDR" ADD CONSTRAINT "ORDR_FK3" FOREIGN KEY ("STATUS")
	  REFERENCES "GOSPODARRZ"."STATUS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USR
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."USR" ADD CONSTRAINT "USR_FK1" FOREIGN KEY ("ADDRESS")
	  REFERENCES "GOSPODARRZ"."ADDRESS" ("ID") ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."USR" ADD CONSTRAINT "USR_FK2" FOREIGN KEY ("PRIVILIGES")
	  REFERENCES "GOSPODARRZ"."PRIVILIGE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USROBJECT
--------------------------------------------------------

  ALTER TABLE "GOSPODARRZ"."USROBJECT" ADD CONSTRAINT "USROBJECT_FK1" FOREIGN KEY ("OBJECT")
	  REFERENCES "GOSPODARRZ"."OBJECT" ("ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "GOSPODARRZ"."USROBJECT" ADD CONSTRAINT "USROBJECT_FK2" FOREIGN KEY ("USR")
	  REFERENCES "GOSPODARRZ"."USR" ("ID") ON DELETE CASCADE ENABLE;
